### ISSUE TITLE
No buttons when using desginated initializer of SBSDKCropViewController

### ISSUE THREAD

**Issue by teameh** [doo/Scanbot-SDK-Examples-iOS#11]
When I the desginated initializer for the `SBSDKCropViewController`:

```
- (nonnull instancetype)initWithParentViewController:(nonnull UIViewController *)parentViewController
                                       containerView:(nonnull UIView *)container;
```

The crop view is displayed but it shows no buttons for canceling or applying the crop. And since there is no "applyCrop" method on the controller it is also not possible to hook up your own buttons.

**Comment by sebastato** [comment]
There are two ways to use SBSDKCropViewController:

1. You create an instance using initWithParentViewController:containerView: 
Then you should provide your own buttons in parentViewController.
You can get the cropped image and/or the current polygon from the SBSDKCropViewController properties "polygon" and "croppedImage".

2. You create an instance using init.
Now push or set the instance to a UINavigationController.
SBSDKCropViewController will now install 2 UIBarButtonItems in your navigation bar, Apply and Cancel.
You implement SBSDKCropViewControllerDelegate.
If you do not pass images for the buttons the buttons will just have text titles.

- (void)cropViewControllerDidCancelChanges:(nonnull SBSDKCropViewController *)cropViewController will be called on your delegate when the cancel-button has been pressed.

- (void)cropViewController:(nonnull SBSDKCropViewController *)cropViewController
didApplyChangesWithPolygon:(nonnull SBSDKPolygon *)polygon
              croppedImage:(nonnull UIImage *)croppedImage will be called when the apply-button has been pressed.

**Comment by teameh** [comment]
Ah, the `croppedImage` property will already be set even before you press the apply buttons? Check, that was not clear from the docs. I'll check it out. 

Thanks.

**Comment by sebastato** [comment]
Actually croppedImage is a lazy property. It is calculated whenever you call the property.

**Comment by teameh** [comment]
Makes sense. Thanks

**Comment by teameh** [comment]
>  I'll check it out.

Yeah that works. Great!

Might be good to add the info you added here to the docs :)
