### ISSUE TITLE
can`t find Language data

### ISSUE THREAD

**Issue by Erickson0806** [doo/Scanbot-SDK-Examples-iOS#3]
ERROR - Language data not found for all specified languages: {(
    en
)} 
 Aborting operation.
 Error Domain=ScanbotSDKErrorDomain Code=9 "The operation couldn’t be completed. (ScanbotSDKErrorDomain error 9.)" UserInfo=0x17d88c20 {ScanbotSDKErrorReason={ScanbotSDKErrorDomain}: Language data for text recognition is missing.}

**Comment by sebastato** [comment]
Yesterday we delivered a major update of Scanbot SDK. Please pull from master branch to update the code and the documentation.

Please read the documentation about languages and how you embedd them in your app.
https://github.com/doo/Scanbot-SDK-Examples-iOS/tree/master/DocumentDetectionDemo/ScanbotSDK/Documentation
Here is the important excerpt from SBSDKOpticalTextRecognizer:

* For each language exists is a training data file. Scanbot SDK ships with no training data files by default to keep 
 * the framework small in size.
 * To install language files and deliver them with your app you must download them, unzip and place the *.traineddata
 * file without any subfolders in your applications bundle in a subfolder named 'SBSDKLanguageData'.
 * Make sure that this folder is copied along with your resources into your app.
 * Language files can be downloaded here https://code.google.com/p/tesseract-ocr/downloads/list
 *
 * Any text recognition operation will fail with an error if all specified languages are missing.
 * If the specified languages are partially available a warning will be logged, but the operation executes
 * without using the missing languages.
 *
 * The number of languages passed to OCR operations have a significant impact on the performance: the more languages,
 * the slower the recognition process.

You can find german and english language data here as the sample app uses it:
https://github.com/doo/Scanbot-SDK-Examples-iOS/tree/master/DocumentDetectionDemo/ScanbotSDK/AdditionalData/SBSDKLanguageData

**Comment by kristinathai** [comment]
I'm getting the same error in the sample demo app that you supplied. I created a folder for the eng.traineddata file called SBSDKLanguageData and placed it in the demo application bundle, but it's still giving me the same error for any OCR related action. Are there any other steps needed?

![screen shot 2015-07-20 at 2 10 39 pm](https://cloud.githubusercontent.com/assets/1186874/8787473/2e0ea2ae-2ee9-11e5-85a8-3701afd3f3bc.png)

**Comment by sebastato** [comment]
Okay, found the problem. There was a problem with a path that was not relative to the project. Sorry, fixed.
